# Configuration for Alacritty, the GPU enhanced terminal emulator.
  env:
    TERM: alacritty

  shell:
    program: /usr/bin/fish

  window:
    padding:
      x: 8
      y: 15
    decorations: full
    startup_mode: Windowed
    title: Terminal

  scrolling:
    history: 10000

  font:
    normal:
      family: Noto Mono Nerd Font Complete
    bold:
      style: Noto Mono Nerd Font Complete

  # Point size
    size: 12

    offset:
      x: 0
      y: -1
  
  cursor:
    style: Beam
  
   # Whale theme
  colors:
      # Default colors
      primary:
        background: '0x1a1e2a'
        foreground: '0xffffff'

      # Normal colors
      normal:
        black:   '0x1d2430'
        red:     '0xfa5ead'
        green:   '0x00fbad'
        yellow:  '0xffdf5f'
        blue:    '0x5eadfc'
        magenta: '0xfa5ead'
        cyan:    '0x3d87d1'
        white:   '0xffffff'

      # Bright colors
      bright:
        black:   '0x1d2430'
        red:     '0xfa5ead'
        green:   '0x00fbad'
        yellow:  '0xffdf5f'
        blue:    '0x5eadfc'
        magenta: '0xfa5ead'
        cyan:    '0x6a6f87'
        white:   '0xeff1f5'
